name: Generate sha256 hashes for release assets

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Asset Hashes
      # https://github.com/MCJack123/ghaction-Generate-Release-Hashes
      uses: MCJack123/ghaction-generate-release-hashes@v3
      with:
        hash-type: sha256
        file-name: asset-hashes.txt

    - name: Upload Hashes to release
      # https://github.com/svenstaro/upload-release-action
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: asset-hashes.txt
        overwrite: true
        asset_name: Files-SHA256-Hashes.txt
        tag: ${{ github.ref }}
