on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

name: Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: python -m build

      - name: Generate Asset Hashes
        # https://github.com/MCJack123/ghaction-Generate-Release-Hashes
        uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: sha256
          file-name: asset-hashes.txt

      - name: Create Github Release
        id: github_release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            asset-hashes.txt
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
